[package]
name = "libtinyos"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[features]
default = []

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
