name: test CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust Nightly
      run: rustup install nightly
      
    - name: Add Rust Components
      run: rustup component add rust-src llvm-tools-preview

    - name: Install target
      run: rustup target add x86_64-unknown-none

    - name: Check Rust environment
      run: |
        rustup show
        rustup component list --installed
